### ISSUE TITLE
News slider not working and the news is broken.

### ISSUE THREAD

**Issue by Tonyt8** [nitsan-technologies/ns_news_slider#3]
Hi,

I test the ns_news_slider before purchasing the full version. It does not work.
My setup:
Typo3 12.9.4
bootstrap_package 14.0.7
introduction 4.6.1
News 11.3.0
numbered_pagination 2.0.0
ns_news_slider 12.0.0

When the page loads the all the news items appear, but there is not slider.
I have now uninstalled the ns_news_slider, but the news tools does not work anymore.
Please can you help?

Regards,
Tony

**Comment by nitsan-technologies** [comment]
Hey Tony,

After reviewing the problem, we didn't encounter it. It seems that you might have omitted the necessary JQuery Library. Make sure to activate JQuery, as illustrated in the attached screenshot from the Constant Editor.

<img width="1280" alt="image" src="https://github.com/nitsan-technologies/ns_news_slider/assets/2622317/aa8df0f3-20ba-4c70-9346-627994dde2a4">

If you continue to experience difficulties, could you grant us access to your TYPO3 instance? Please send the details via private message to support at t3planet.com ;)

Cheers, Team NITSAN
